name: Exam CI/CD workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Build & install dependencies
        run: npm install
      - name: Run Unit tests
        run: npm run test:unit
      - name: Display SoftUni username
        run: echo "qceka88"